// Generated by scripts/fetch-inaturalist-discovery.mjs — do not hand-edit.
// Aggregate research-grade species counts and public iNaturalist search URLs;
// no observation coordinates are stored here.
import type { INaturalistDiscoveryTrail } from "./types";

export const inaturalistDiscoveryGeneratedAt = "2026-07-07";

export const inaturalistDiscoveryTrails = [
  {
    id: "animal-atlas",
    label: "The wide door",
    title: "Every animal logged nearby",
    description:
      "Move past the shortlist into a species-first atlas of community-documented animals—from familiar reef residents to insects no guide card could hold.",
    fieldPrompt:
      "Pick the strangest silhouette, then learn one field mark before opening its observations.",
    accent: "tidepool",
    speciesCount: 926,
    url: "https://www.inaturalist.org/observations?lat=20.7049&lng=-156.4465&radius=50&d1=2025-07-07&quality_grade=research&captive=false&photos=true&taxon_id=1&view=species&subview=grid",
    generatedAt: "2026-07-07",
  },
  {
    id: "reef-fish",
    label: "Shape school",
    title: "Reef fish, species by species",
    description:
      "Compare surgeonfish, wrasses, butterflyfish, eels, and other ray-finned neighbors in a visual species grid built from local records.",
    fieldPrompt:
      "Choose one body shape—disc, needle, ribbon, or torpedo—and see how many variations the reef made.",
    accent: "mango",
    speciesCount: 192,
    url: "https://www.inaturalist.org/observations?lat=20.7049&lng=-156.4465&radius=50&d1=2025-07-07&quality_grade=research&captive=false&photos=true&taxon_id=47178&view=species&subview=grid",
    generatedAt: "2026-07-07",
  },
  {
    id: "nudibranchs",
    label: "Tiny weirdos",
    title: "The nudibranch kaleidoscope",
    description:
      "Sea slugs reward a slower scale of looking: branching backs, impossible colors, mimicry, camouflage, and species smaller than a thumb.",
    fieldPrompt:
      "Find one that looks like coral, one like a leaf, and one like something from another planet.",
    accent: "coral",
    speciesCount: 32,
    url: "https://www.inaturalist.org/observations?lat=20.7049&lng=-156.4465&radius=50&d1=2025-07-07&quality_grade=research&captive=false&photos=true&taxon_id=47113&view=species&subview=grid",
    generatedAt: "2026-07-07",
  },
  {
    id: "birds",
    label: "Coast to crater",
    title: "Maui’s bird spectrum",
    description:
      "Open one species reel spanning wetland stilts, seabirds, summit endemics, forest birds, and the introduced neighbors mixed among them.",
    fieldPrompt:
      "Sort by color in your head: red forest bird, black-and-white wetland bird, brown ground bird.",
    accent: "bird",
    speciesCount: 81,
    url: "https://www.inaturalist.org/observations?lat=20.7049&lng=-156.4465&radius=50&d1=2025-07-07&quality_grade=research&captive=false&photos=true&taxon_id=3&view=species&subview=grid",
    generatedAt: "2026-07-07",
  },
  {
    id: "conservation-watch",
    label: "Handle with care",
    title: "Threatened species evidence",
    description:
      "A conservation-status filter reveals which nearby records carry extra ecological weight without turning obscured locations into destination pins.",
    fieldPrompt:
      "Read the species story first; treat the map as regional evidence and keep every encounter low-impact.",
    accent: "mist",
    speciesCount: 56,
    url: "https://www.inaturalist.org/observations?lat=20.7049&lng=-156.4465&radius=50&d1=2025-07-07&quality_grade=research&captive=false&photos=true&taxon_id=1&threatened=true&view=species&subview=grid",
    generatedAt: "2026-07-07",
  },
  {
    id: "plants-and-fungi",
    label: "Beyond animals",
    title: "Plants, fungi, and lichens",
    description:
      "Species discovery does not stop when the creature cards end. Follow the same community lens into flowers, ferns, mushrooms, and lichens.",
    fieldPrompt:
      "Look for three textures—silver, waxy, and lace-like—without picking or leaving the trail.",
    accent: "leaf",
    speciesCount: 870,
    url: "https://www.inaturalist.org/observations?lat=20.7049&lng=-156.4465&radius=50&d1=2025-07-07&quality_grade=research&captive=false&photos=true&taxon_ids=47126%2C47170&view=species&subview=grid",
    generatedAt: "2026-07-07",
  },
] satisfies INaturalistDiscoveryTrail[];
